routes/web.php
<?php

use App\Http\Controllers\LikesController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', "PostController@index")->name("newsfeed");

Auth::routes();

// Profile

Route::middleware("auth")->group(function(){
    // Post
    Route::resource("/post", "PostController");
    // Post like
    Route::post("/like", [LikesController::class, "like"])->name("like.like");
    Route::post("/unlike", [LikesController::class, "unlike"])->name("like.unlike");

    Route::prefix("/profile")->group(function(){
        Route::get('/', "ProfileController@index")->name("profile");
        Route::view("/edit", "profile.edit")->name("profile.edit");
        Route::post("/edit", "ProfileController@profileUpdate")->name("profile.update");
        Route::post("/edit/profile-picture", "ProfileController@profilePictureUpdate")->name("profile.pictureUpdate");
    });

});

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
protected $fillable = ["title", "description"];
    public function images(){
        return $this->hasMany(PostPhoto::class);
    }

    public function post_owner(){
        return $this->belongsTo(User::class, "user_id");
    }

    public function totalLikes(){
       return $this->hasMany(Like::class,"post_id");
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Post;
use App\PostPhoto;
use App\User;
use Auth;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Facades\Storage;

class PostController extends Controller
{
    public function index(){
        return view("newsfeed", [
            "posts" => Post::all(),
        ])->with(["images", "post_owner","postLikes"]);
    }

    public function create(){
        return view("post.create");
    }

    public function store(Request $request){
        if ($request->hasFile("post-img.*")) {
            $fileNameArr = [];
            foreach ($request->file("post-img.*") as $file) {
                $newName = uniqid() . "_post-img." . $file->getClientOriginalExtension();
                array_push($fileNameArr, $newName);
                $file->storeAs('public/post', $newName);
            }
        }

        $request->validate([
            "title" => "required|string|min:4|max:255",
            "description" => "required|string|min:10|",
            "post-img.*" => "mimetypes:image/jpeg,image/png"
        ]);
        $post = new Post();
        $post->title = $request->title;
        $post->description = $request->description;
        $post->user_id = Auth::id();
        $post->save();

        if (isset($fileNameArr)) {
            foreach ($fileNameArr as $fileName) {
                $postPhoto = new PostPhoto();
                $postPhoto->post_id = $post->id;
                $postPhoto->filename = $fileName;
                $postPhoto->save();
            }
        }
        return redirect()->route("newsfeed");
    }

    public function show(Post $post){
        //
    }

    public function edit(Post $post){
        if (Gate::allows("post_owner", $post)) {
            return view("post.edit", [
                "post" => $post
            ]);
        }
        return abort(404);
    }

    public function update(Request $request, Post $post){
        if (Gate::allows("post_owner", $post)) {
            if ($request->hasFile("post-img.*")) {
                $fileNameArr = [];
                foreach ($request->file("post-img.*") as $file) {
                    $newName = uniqid() . "_post-img." . $file->getClientOriginalExtension();
                    array_push($fileNameArr, $newName);
                    $file->storeAs('public/post', $newName);
                }
                // Deleting previous photos
                foreach ($post->images as $image) {
                    Storage::delete("public/post/" . $image->filename);
                }
                $toDelete = $post->images->pluck("id");
                PostPhoto::destroy($toDelete);
            }

            $request->validate([
                "title" => "required|string|min:4|max:255",
                "description" => "required|string|min:10|",
                "post-img.*" => "mimetypes:image/jpeg,image/png"
            ]);
            $post->title = $request->title;
            $post->description = $request->description;
            $post->user_id = Auth::id();
            $post->update();

            if (isset($fileNameArr)) {
                foreach ($fileNameArr as $fileName) {
                    $postPhoto = new PostPhoto();
                    $postPhoto->post_id = $post->id;
                    $postPhoto->filename = $fileName;
                    $postPhoto->save();
                }
            }
            return redirect()->route("newsfeed");
        }
        return abort(404);
    }

    public function destroy(Post $post){
        if (Gate::allows("post_owner", $post)) {
            if (isset($post->images)) {
                foreach ($post->images as $image) {
                    Storage::delete("public/post/" . $image->filename);
                }
                $toDelete = $post->images->pluck("id");
                PostPhoto::destroy($toDelete);
            }
            $title = $post->title;
            $post->delete();
            return redirect()->route("newsfeed")->with("status", "$title is deleted");
        }
        return abort(404);
    }
}

app/View/Components/Post.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class Post extends Component
{
    public $post;

    /**
     * Create a new component instance.
     *
     * @return void
     */
    public function __construct($post){
        $this->post = $post;
    }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\View\View|string
     */
    public function render(){
        return view('components.post');
    }
}

resources/views/post/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-8">
                <div class="card mb-3 p-3">
                    <form action="{{ route('post.store') }}" class="" enctype="multipart/form-data" method="post">
                        @csrf
                        <h3 class="card-title text-center text-primary font-weight-bold">Add Post</h3>
                        <div class="mb-2">
                            <label for="title" class="h3">Title</label>
                            <input type="text" id="title" class="form-control @error("title") is-invalid @enderror"
                                   name="title" value="{{ old("title") }}">
                            @error("title")
                            <span class="text-danger">{{ $message }}</span>
                            @enderror
                        </div>
                        <div class="mb-2">
                            <label for="description" class="h3">Description</label>
                            <textarea name="description" id="description" cols="30" rows="10"
                                      class="form-control @error("title") is-invalid @enderror">{{ old("description") }}</textarea>
                            @error("description")
                            <span class="text-danger">{{ $message }}</span>
                            @enderror
                        </div>
                        <div class="mb-2 d-flex justify-content-between">
                            <div class="">
                                <input type="file" class="form-control-file" name="post-img[]"
                                       accept="image/jpeg,image/png" multiple>
                                @error("post-img.*")
                                <span class="text-danger">{{ $message }}</span>
                                @enderror
                            </div>
                            <button type="submit" class="btn btn-primary"><i class="fas fa-plus-circle"></i> Add Post
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection
@section("script")
    <script>

    </script>
@endsection

resources/views/post/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-8">
                <div class="card mb-3 p-3">
                    <form action="{{ route('post.update',$post->id) }}" class="" enctype="multipart/form-data"
                          method="post">
                        @csrf
                        @method("put")
                        <h3 class="card-title text-center text-primary font-weight-bold">Edit Post</h3>
                        <div class="mb-2">
                            <label for="title" class="h3">Title</label>
                            <input type="text" id="title" class="form-control @error("title") is-invalid @enderror"
                                   name="title" value="{{ (old("title"))?old("title"):$post->title }}">
                            @error("title")
                            <span class="text-danger">{{ $message }}</span>
                            @enderror
                        </div>
                        <div class="mb-2">
                            <label for="description" class="h3">Description</label>
                            <textarea name="description" id="description" cols="30" rows="10"
                                      class="form-control @error("title") is-invalid @enderror">{{ (old("description"))?old("description"):$post->description }}</textarea>
                            @error("description")
                            <span class="text-danger">{{ $message }}</span>
                            @enderror
                        </div>
                        <div class="mb-2 d-flex justify-content-between">
                            <div class="">
                                <input type="file" class="form-control-file" name="post-img[]"
                                       accept="image/jpeg,image/png" multiple>
                                @error("post-img.*")
                                <span class="text-danger">{{ $message }}</span>
                                @enderror
                            </div>
                            <button type="submit" class="btn btn-primary"><i class="fas fa-edit"></i>Edit Post
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection
@section("script")
    <script>

    </script>
@endsection